# Generated by Django 5.1.2 on 2024-10-09 18:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycollection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coleccion',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='valor',
        ),
        migrations.AddField(
            model_name='comic',
            name='estado',
            field=models.CharField(choices=[('que me faltan', 'que me faltan'), ('disponibles para canje', 'disponibles para canje'), ('en la biblioteca', 'en la biblioteca'), ('Variant Cover', 'Variant Cover')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coleccion',
            name='comic',
            field=models.ManyToManyField(related_name='colecciones', to='mycollection.comic'),
        ),
    ]
